version: '3'

services:
  web:
    image: ghcr.io/lab-pository/hello-virtual-thread:v0.0.2
    ports:
      - "8080:8080"
      - "9091:9091"
  master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://web:8080 --users 50 --spawn-rate 50 --run-time "1m"
  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
