spring:
  application:
    name: hello-virtual-thread
  threads:
    virtual:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none

server:
  tomcat:
    threads:
      max: 1
      min-spare: 1
